# testing frondend
language: node_js
node_js:
  - "6"
# testing building docker container
services:
  - docker
before_install:
  - ln -s ./docker/docker-compose.yml ./docker-compose.yml
  - docker-compose build