sudo: required
services:
  - docker
before_install:
  - ln -s ./docker/docker-compose.yml ./docker-compose.yml
  - docker-compose build
# testing inside docker container
# we also test building of docker image
script:
  - docker-compose run --rm server test
